export default {
  projectTypeOptions: [
    { value: null, text: "Please select an option" },
    { value: "Asset Management", text: "Asset Management" },
    { value: "Energy Audit", text: "Energy Audit" },
    { value: "Facility Assessment", text: "Facility Assessment" },
    { value: "New Commissioning", text: "New Commissioning" },
    { value: "Re Commissioning", text: "Re Commissioning" },
    { value: "Retro Commissioning", text: "Retro Commissioning" },
  ],

  industryOptions: [
    { value: null, text: "Please select an option" },
    { value: "Commercial", text: "Commercial" },
    { value: "Federal", text: "Federal" },
    { value: "Health", text: "Health" },
    { value: "Higer Education", text: "Higer Education" },
    { value: "Industrial", text: "Industrial" },
    { value: "K-12", text: "K-12" },
    { value: "Local Government", text: "Local Government" },
    { value: "State", text: "State" },
  ],

  buildingTypeOptions: [
    { value: null, text: "Please select an option" },
    { value: "Appartments", text: "Appartments" },
    { value: "Church", text: "Church" },
    { value: "Correctional Facility", text: "Correctional Facility" },
    { value: "Hospital", text: "Hospital" },
    { value: "High Rise", text: "High Rise" },
    { value: "Hotel", text: "Hotel" },
    { value: "Industrial", text: "Industrial" },
    { value: "Laboratory", text: "Laboratory" },
    { value: "Large Mall", text: "Large Mall" },
    { value: "Large Office", text: "Large Office" },
    { value: "Library", text: "Library" },
    { value: "Medium Office", text: "Medium Office" },
    { value: "Small Office", text: "Small Office" },
    { value: "State Building", text: "State Building" },
    { value: "Store", text: "Store" },
    { value: "Multipurpose", text: "Multipurpose" },
    { value: "Warehouse", text: "Warehouse" },
  ],

  statusOptions: [
    { value: null, text: "Please select an option" },
    { value: "Construction", text: "Construction" },
    { value: "Design", text: "Design" },
    { value: "Not Started", text: "Not Started" },
    { value: "Post Warranty", text: "Post Warranty" },
    { value: "Pre Design", text: "Pre Design" },
    { value: "RFP", text: "RFP" },
    { value: "Testing", text: "Testing" },
    { value: "Warranty", text: "Warranty" },
  ],

  userStatusOptions: [
    { value: null, text: "Please select an option" },
    { value: "accepted", text: "Accepted" },
    { value: "invited", text: "Invited" },
    { value: "member", text: "Member" },
    { value: "rejected", text: "Rejected" },
  ],

  roleOptions: [
    { value: null, text: "Please select a role" },
    { value: "Architect", text: "Architect" },
    { value: "Client", text: "Client" },
    { value: "Controls Contractor", text: "Controls Contractor" },
    { value: "CxA", text: "CxA" },
    { value: "Electrical Contractor", text: "Electrical Contractor" },
    { value: "Engineer", text: "Engineer" },
    { value: "General Contractor", text: "General Contractor" },
    { value: "Mechanical Contractor", text: "Mechanical Contractor" },
    { value: "Other Contractor", text: "Other Contractor" },
    { value: "Plumbing Contractor", text: "Plumbing Contractor" },
    { value: "TAB Contractor", text: "TAB Contractor" },
    { value: "User", text: "User" },
  ],

  activityOptions: [
    { value: null, text: "Please select an option" },
    { value: "BOD Review", text: "BOD Review" },
    { value: "Construction Checklist", text: "Construction Checklist" },
    { value: "Design Review", text: "Design Review" },
    { value: "Equipment Startup Review", text: "Equipment Startup Review" },
    { value: "Functional Test", text: "Functional Test" },
    { value: "Installation Review", text: "Installation Review" },
    { value: "OPR Review", text: "OPR Review" },
    { value: "Owner Manual Review", text: "Owner Manual Review" },
    { value: "Seasonal Test", text: "Seasonal Test" },
    { value: "Submittal Review", text: "Submittal Review" },
    { value: "Test and Balance Review", text: "Test and Balance Review" },
    { value: "Training Review", text: "Training Review" },
  ],

  issueTypes: [
    { value: null, text: "Select type" },
    { value: "assessment", text: "Assessment" },
    { value: "checklist", text: "Checklist" },
    { value: "construction", text: "Construction Review" },
    { value: "design", text: "Design Review" },
    { value: "documentation", text: "O & M Manual Review" },
    { value: "FPT", text: "Functional Testing" },
    { value: "installation", text: "Installation Review" },
    { value: "leed", text: "LEED Review" },
    { value: "submittal", text: "Submittal Review" },
    { value: "startup", text: "Equipment Startup" },
    { value: "TAB", text: "Test & Balance" },
    { value: "training", text: "Training Review" },
  ],

  issuePriorities: [
    { value: null, text: 'Select priority' },
    { value: "comment", text: "Comment" },
    { value: 'critical', text: 'Critical' },
    { value: 'high', text: 'High' },
    { value: 'low', text: 'Low' },
    { value: 'medium', text: 'Medium' },
  ],

  issueStatuses: [
    { value: null, text: "Select a status" },
    { value: "canceled", text: "Canceled" },
    { value: "closed", text: "Closed" },
    { value: "open", text: "Open" },
    { value: "pending", text: "Pending" },
    { value: "resolved", text: "Resolved" },
  ],

  checklistStatuses: [
    { value: null, text: "Please select an option" },
    { value: "not started", text: "Not Started" },
    { value: "started", text: "Started" },
    { value: "progress", text: "Progress" },
    { value: "completed", text: "Completed" },
    { value: "cancelled", text: "Cancelled" },
  ],


  eventStatuses: [
    { value: null, text: "Please select an option" },
    { value: "cancelled", text: "Cancelled" },
    { value: "completed", text: "Completed" },
    { value: "progress", text: "Progress" },
    { value: "pending", text: "Pending" },
    { value: "scheduled", text: "Scheduled" },
  ],

  systemOptions: [
    { value: null, text: "Please select an option" },
    { value: "mechanical", text: "Mechanical" },
    { value: "electrical", text: "Electrical" },
    { value: "plumbing", text: "Plumbing" },
    { value: "life safety", text: "Life Safety" },
    { value: "test & balance", text: "Test & Balance" },
    { value: "controls", text: "Controls" },
    { value: "lighting_controls", text: "Lighting Controls" },
    { value: "lighting", text: "Lighting" },
    { value: "photovoltaic", text: "Photovoltaic" },
  ],

  divisionOptions: [
    { value: null, text: "Please select an option" },
    { value: "00", text: "Division 00 - Procurement and Contracting Requirements" },
    { value: "01", text: "Division 01 - General Requirements" },
    { value: "02", text: "Division 02 - Existing Conditions" },
    { value: "03", text: "Division 03 - Concrete" },
    { value: "04", text: "Division 04 - Masonry" },
    { value: "05", text: "Division 05 - Metals" },
    { value: "06", text: "Division 06 - Wood, Plastics, Composites" },
    { value: "07", text: "Division 07 - Thermal and Moisture Protection" },
    { value: "08", text: "Division 08 - Openings" },
    { value: "09", text: "Division 09 - Finishes" },
    { value: "10", text: "Division 10 - Specialties" },
    { value: "11", text: "Division 11 - Equipment" },
    { value: "12", text: "Division 12 - Furnishings" },
    { value: "13", text: "Division 13 - Special Construction" },
    { value: "14", text: "Division 14 - Conveying Equipment" },
    { value: "21", text: "Division 21 - Fire Suppression" },
    { value: "22", text: "Division 22 - Plumbing" },
    { value: "23", text: "Division 23 - Heating, Ventilating, and Air Conditioning (HVAC)" },
    { value: "25", text: "Division 25 - Integrated Automation" },
    { value: "26", text: "Division 26 - Electrical" },
    { value: "27", text: "Division 27 - Communications" },
    { value: "28", text: "Division 28 - Electronic Safety and Security" },
    { value: "31", text: "Division 31 - Earthwork" },
    { value: "32", text: "Division 32 - Exterior Improvements" },
    { value: "33", text: "Division 33 - Utilities" },
    { value: "34", text: "Division 34 - Transportation" },
    { value: "35", text: "Division 35 - Waterway and Marine Construction" },
    { value: "40", text: "Division 40 - Process Integration" },
    { value: "41", text: "Division 41 - Material Processing and Handling Equipment" },
    { value: "42", text: "Division 42 - Process Heating, Cooling, and Drying Equipment" },
    { value: "43", text: "Division 43 - Process Gas and Liquid Handling, Purification and Storage Equipment" },
    { value: "44", text: "Division 44 - Pollution and Waste Control Equipment" },
    { value: "45", text: "Division 45 - Industry-Specific Manufacturing Equipment" },
    { value: "46", text: "Division 46 - Water and Wastewater Equipment" },
    { value: "48", text: "Division 48 - Electrical Power Generation" },
  ],

  equipmentTypes: [
    { value: "", text: "All"},
    { value: "", text: "-- mechanical --"},
    { value:"AHU", text: "Air Handler"},
    { value:"ERU", text: "Energy Recovery Unit"},
    { value:"FCU", text: "Fancoil Unit"},
    { value:"VAV", text: "VAV Box"},
    { value: "heat pump", text: "Heat Pump" },
    { value: "TU", text: "Terminal Unit" },
    { value:"heater", text: "Unit Heater"},
    { value:"chiller", text: "Chiller"},
    { value:"boiler", text: "Boiler"},
    { value:"pump", text: "HVAC Pump"},
    { value:"fan", text: "Fan"},
    { value: "", text: "-- electrical --"},
    { value:"panelboard", text: "Panelboard"},
    { value:"switchgear", text: "Switchgear"},
    { value:"generator", text: "Generator"},
    { value:"ATS", text: "Automatic Transfer Switch"},
    { value:"transformer", text: "Transformer"},
    { value: "PVSystem", text: "Photvoltaic System" },
    { value: "", text: "-- plumbing --"},
    { value:"water heater", text: "Water Heater"},
    { value:"booster", text: "Booster Pump"},
    { value:"circ pump", text: "Circulation Pump"},
    { value:"sump pump", text: "Sump Pump"},
  ],

  checklistTypes: [
    { value: null, text: "Please select an option" },
    { value: "functional test", text: "Functional Test" },
    { value: "pre-functional", text: "Pre-functional" },
    { value: "QC", text: "QC" },
  ],

  fptTypes: [
    { value: null, text: "Please select an option" },
    { value: "preliminary", text: "Preliminary Checks" },
    { value: "ai", text: "Analog Inputs" },
    { value: "ao", text: "Anolog Outputs" },
    { value: "di", text: "Digital Inputs" },
    { value: "do", text: "Digital Outputs" },
    { value: "setpoints", text: "Setpoints" },
    { value: "alarms", text: "Alarms" },
    { value: "sequences", text: "Sequences" },
  ],

  assetStatuses: [
    { value: null, text: "Please select an option" },
    { value: "No Action", text: "No Action" },
    { value: "On Order", text: "On Order" },
    { value: "Shipped", text: "Shipped" },
    { value: "In Storage", text: "In Storage" },
    { value: "Delivered", text: "Delivered" },
    { value: "Installed", text: "Installed" },
    { value: "Set", text: "Set" },
    { value: "Installed", text: "Installed" },
    { value: "Ready for FPT", text: "Ready for FPT" },
    { value: "Tested", text: "Tested" },
    { value: "Trained", text: "Trained" }
  ],
}


